import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BookOpen, ChevronDown, CircleDollarSign, Coffee, Download, GraduationCap, Moon, Pencil, Plus, Search, ShoppingBag, Sparkles, Sun, TrainFront, Trash2, Utensils, WalletCards } from 'lucide-react'

const categories = ['Food & Dining', 'Transport', 'Education', 'Entertainment', 'Shopping', 'Health', 'Other']
const styles = { 'Food & Dining': 'food', Transport: 'transport', Education: 'education', Entertainment: 'entertainment', Shopping: 'shopping', Health: 'health', Other: 'other' }
const chartColors = { 'Food & Dining': '#c68a5d', Transport: '#7d9aa8', Education: '#9a91c4', Entertainment: '#b8819e', Shopping: '#b99b62', Health: '#78a28f', Other: '#7e858e' }
const seed = [{ id: '1', amount: 245, category: 'Food & Dining', description: 'Lunch at campus cafe', date: '2026-08-06' }, { id: '2', amount: 120, category: 'Transport', description: 'Metro recharge', date: '2026-08-05' }, { id: '3', amount: 799, category: 'Education', description: 'JavaScript course', date: '2026-08-03' }]
const money = (n) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(n)
const readableDate = (date) => new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T12:00:00`))
const initialForm = () => ({ amount: '', category: 'Food & Dining', description: '', date: new Date().toISOString().slice(0, 10) })
function loadExpenses() { try { const saved = JSON.parse(localStorage.getItem('student-expenses')); return Array.isArray(saved) ? saved : seed } catch { return seed } }
function loadBudgets() { try { const saved = JSON.parse(localStorage.getItem('student-expense-budgets')); return saved && typeof saved === 'object' && !Array.isArray(saved) ? saved : {} } catch { return {} } }
function readTheme() { try { return localStorage.getItem('expense-theme') === 'dark' } catch { return true } }
function persist(key, value) { try { localStorage.setItem(key, value) } catch { /* Storage can be unavailable in private or embedded contexts. */ } }
function isInDateRange(date, range) { if (range === 'all') return true; const today = new Date(); today.setHours(0, 0, 0, 0); const value = new Date(`${date}T12:00:00`); if (range === 'today') return value.getTime() === today.getTime(); if (range === 'week') { const start = new Date(today); start.setDate(today.getDate() - ((today.getDay() + 6) % 7)); return value >= start && value <= today } if (range === 'month') return value.getFullYear() === today.getFullYear() && value.getMonth() === today.getMonth(); const start = new Date(today); start.setDate(today.getDate() - 29); return value >= start && value <= today }
function csvValue(value) { return `"${String(value).replaceAll('"', '""')}"` }
function piePoint(angle) { const radians = ((angle - 90) * Math.PI) / 180; return { x: 50 + 42 * Math.cos(radians), y: 50 + 42 * Math.sin(radians) } }
function pieSlice(start, end) { if (end - start >= 359.99) return 'M 50 8 A 42 42 0 1 1 49.99 8 Z'; const from = piePoint(start); const to = piePoint(end); return `M 50 50 L ${from.x} ${from.y} A 42 42 0 ${end - start > 180 ? 1 : 0} 1 ${to.x} ${to.y} Z` }

export default function App() {
  const [expenses, setExpenses] = useState(loadExpenses)
  const [dark, setDark] = useState(readTheme)
  const [editing, setEditing] = useState(null)
  const [filter, setFilter] = useState('All categories')
  const [dateRange, setDateRange] = useState('all')
  const [search, setSearch] = useState('')
  const [form, setForm] = useState(initialForm)
  const [budgets, setBudgets] = useState(loadBudgets)
  const [exporting, setExporting] = useState(false)
  useEffect(() => { persist('student-expenses', JSON.stringify(expenses)) }, [expenses])
  useEffect(() => { persist('student-expense-budgets', JSON.stringify(budgets)) }, [budgets])
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); persist('expense-theme', dark ? 'dark' : 'light') }, [dark])
  const shown = useMemo(() => expenses.filter((x) => (filter === 'All categories' || x.category === filter) && (x.description || '').toLowerCase().includes(search.toLowerCase()) && isInDateRange(x.date, dateRange)).sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0)), [expenses, filter, search, dateRange])
  const summary = useMemo(() => { const grouped = shown.reduce((result, x) => { result[x.category] = (result[x.category] || 0) + Number(x.amount || 0); return result }, {}); const total = shown.reduce((sum, x) => sum + Number(x.amount || 0), 0); return { total, grouped, top: shown.length ? Object.entries(grouped).sort((a, b) => b[1] - a[1])[0][0] : '—' } }, [shown])
  const chartData = useMemo(() => { const grouped = shown.reduce((result, x) => { result[x.category] = (result[x.category] || 0) + Number(x.amount || 0); return result }, {}); return Object.entries(grouped).sort((a, b) => b[1] - a[1]).map(([name, amount]) => ({ name, amount })) }, [shown])
  const chartTotal = useMemo(() => shown.reduce((sum, x) => sum + Number(x.amount || 0), 0), [shown])
  const monthlySpending = useMemo(() => { const month = new Date().toISOString().slice(0, 7); return expenses.filter((x) => (x.date || '').startsWith(month)).reduce((result, x) => { result[x.category] = (result[x.category] || 0) + Number(x.amount || 0); return result }, {}) }, [expenses])
  const update = (key) => (e) => setForm({ ...form, [key]: e.target.value })
  function save(e) { e.preventDefault(); const item = { ...form, amount: Number(form.amount) }; setExpenses((all) => editing ? all.map((x) => x.id === editing ? { ...item, id: editing } : x) : [{ ...item, id: crypto.randomUUID() }, ...all]); setEditing(null); setForm(initialForm()) }
  function edit(x) { setEditing(x.id); setForm({ amount: x.amount, category: x.category, description: x.description, date: x.date }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  function cancel() { setEditing(null); setForm(initialForm()) }
  function exportCsv() { setExporting(true); const rows = [['Date', 'Description', 'Category', 'Amount'], ...shown.map((x) => [x.date, x.description, x.category, x.amount])]; const csv = rows.map((row) => row.map(csvValue).join(',')).join('\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `expenses-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); window.setTimeout(() => setExporting(false), 350) }

  return <main className="app-shell"><div className="ambient ambient-one" /><div className="ambient ambient-two" /><div className="app-frame">
    <header className="topbar"><a className="brand" href="#top" aria-label="Spendwise dashboard"><span className="brand-mark"><Sparkles size={17} strokeWidth={2.3} /></span><span><strong>Spendwise</strong><small>Know where your money goes.</small></span></a><div className="topbar-actions"><span className="status-dot">Local workspace</span><button type="button" onClick={() => setDark(!dark)} aria-label="Toggle color mode" className="icon-button">{dark ? <Sun size={18} /> : <Moon size={18} />}</button></div></header>
    <section className="intro" id="top"><div><p className="eyebrow">Overview</p><h1>Make every rupee<br /><em>feel intentional.</em></h1></div><p className="intro-copy">A quiet, focused view of the habits behind your spending.</p></section>
    <section className="summary-grid"><Stat label="Total spent" value={money(summary.total)} icon={<WalletCards size={19} />} /><Stat label="Transactions" value={shown.length} icon={<CircleDollarSign size={19} />} /><Stat label="Leading category" value={summary.top} icon={<Sparkles size={18} />} subtle /></section>
    <CategoryChart data={chartData} total={chartTotal} />
    <BudgetPanel budgets={budgets} spending={monthlySpending} onChange={(category, value) => setBudgets((current) => ({ ...current, [category]: value }))} />
    <section className="entry-panel"><div className="panel-heading"><div><p className="eyebrow">{editing ? 'Updating record' : 'New record'}</p><h2>{editing ? 'Refine an expense' : 'Add an expense'}</h2></div>{editing && <button type="button" onClick={cancel} className="text-button">Discard changes</button>}</div><form onSubmit={save} className="expense-form"><Field label="Amount" type="number" value={form.amount} onChange={update('amount')} placeholder="0" min="1" step="1" required /><Field label="Description" value={form.description} onChange={update('description')} placeholder="What was this for?" required /><Select label="Category" value={form.category} onChange={update('category')} options={categories} /><Field label="Date" type="date" value={form.date} onChange={update('date')} required /><button className="submit-button"><span>{editing ? 'Save changes' : 'Add expense'}</span><Plus size={17} /></button></form></section>
    <section className="ledger"><div className="ledger-header"><div><p className="eyebrow">Ledger</p><h2>Recent activity</h2><p className="muted-copy">{shown.length} record{shown.length !== 1 ? 's' : ''} shown</p></div><div className="ledger-tools"><label className="search-field"><Search size={16} /><span className="sr-only">Search expenses</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search expenses" /></label><label className="select-inline"><span className="sr-only">Filter by category</span><select value={filter} onChange={(e) => setFilter(e.target.value)}><option>All categories</option>{categories.map((x) => <option key={x}>{x}</option>)}</select><ChevronDown size={15} /></label><button type="button" onClick={exportCsv} disabled={!shown.length || exporting} className="export-button"><Download size={15} />{exporting ? 'Exporting' : 'Export CSV'}</button></div></div><div className="range-filters" aria-label="Filter expenses by date range">{[['today', 'Today'], ['week', 'This Week'], ['month', 'This Month'], ['30days', 'Last 30 Days'], ['all', 'All Time']].map(([value, label]) => <button type="button" key={value} onClick={() => setDateRange(value)} aria-pressed={dateRange === value}>{label}</button>)}</div><div className="expense-list">{shown.map((x) => <Expense key={x.id} item={x} onEdit={() => edit(x)} onDelete={() => setExpenses((all) => all.filter((e) => e.id !== x.id))} />)}{!shown.length && <EmptyState />}</div></section>
    <footer>Spendwise · Your data stays in this browser</footer>
  </div></main>
}
function Stat({ label, value, icon, subtle }) { return <article className={`stat-card ${subtle ? 'stat-subtle' : ''}`}><div className="stat-label"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong></article> }
function Field({ label, ...props }) { return <label className="field-label"><span>{label}</span><input {...props} /></label> }
function Select({ label, options, ...props }) { return <label className="field-label"><span>{label}</span><div className="select-wrap"><select {...props}>{options.map((x) => <option key={x}>{x}</option>)}</select><ChevronDown size={15} /></div></label> }
function BudgetPanel({ budgets, spending, onChange }) { return <section className="budget-panel"><div className="budget-title"><div><p className="eyebrow">Monthly limits</p><h2>Budgets, at a glance</h2><p className="muted-copy">Set a gentle ceiling for every category.</p></div><span>Current month</span></div><div className="budget-grid">{categories.map((category) => { const budget = Number(budgets[category]) || 0; const spent = spending[category] || 0; const percentage = budget ? (spent / budget) * 100 : 0; const state = percentage >= 100 ? 'danger' : percentage >= 80 ? 'warning' : 'normal'; const remaining = budget - spent; return <article className="budget-card" key={category}><div className="budget-card-top"><span className={`category-tag ${styles[category]}`}>{category}</span><label><span className="sr-only">Monthly budget for {category}</span><span>₹</span><input aria-label={`Monthly budget for ${category}`} type="number" min="0" step="1" value={budgets[category] ?? ''} onChange={(e) => onChange(category, e.target.value === '' ? '' : Math.max(0, Number(e.target.value)))} placeholder="Set limit" /></label></div><div className="budget-figures"><strong>{money(spent)} <small>/ {budget ? money(budget) : 'No limit'}</small></strong>{budget ? <span className={state}>{remaining >= 0 ? `${money(remaining)} left` : `${money(Math.abs(remaining))} over`}</span> : <span>Set a monthly goal</span>}</div><div className={`budget-progress ${state}`}><i style={{ width: `${Math.min(percentage, 100)}%` }} /></div>{budget && percentage >= 100 && <p className="budget-warning"><AlertTriangle size={13} /> This category is over its monthly limit.</p>}</article> })}</div></section> }
function CategoryChart({ data, total }) { const [active, setActive] = useState(null); let progress = 0; const summary = data.map(({ name, amount }) => `${name}: ${money(amount)}`).join(', '); const current = active || { name: 'Spend', amount: total, share: null }; const toggle = (detail) => setActive((selected) => selected?.name === detail.name ? null : detail); return <section className="chart-panel"><div className="chart-title"><div><p className="eyebrow">Allocation</p><h2>Where it’s going</h2></div><span className="chart-total">{money(total)} <small>in current view</small></span></div>{data.length && total > 0 ? <div className="chart-content"><div className="pie"><svg viewBox="0 0 100 100" role="img" aria-label={`Pie chart of spending by category. ${summary}`}>{data.map(({ name, amount }) => { const share = (amount / total) * 100; const start = progress; const end = start + share * 3.6; progress += share * 3.6; const detail = { name, amount, share: Math.round(share) }; const selected = active?.name === name; return <path key={name} className={`chart-slice ${selected ? 'is-active' : ''}`} d={pieSlice(start, end)} fill={chartColors[name]} tabIndex="0" role="button" aria-pressed={selected} aria-label={`${name}: ${money(amount)}, ${Math.round(share)} percent. Select to inspect.`} onClick={() => toggle(detail)} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); toggle(detail) } }} onMouseEnter={() => setActive(detail)}><title>{name}: {money(amount)} ({Math.round(share)}%)</title></path> })}<circle className="pie-core" cx="50" cy="50" r="22" /><text className="pie-label" x="50" y="47" textAnchor="middle">{current.name}</text><text className="pie-value" x="50" y="54" textAnchor="middle">{money(current.amount)}</text>{current.share !== null && <text className="pie-note" x="50" y="60" textAnchor="middle">{current.share}% of view</text>}</svg></div><ul className="chart-legend">{data.map(({ name, amount }) => <li key={name} onMouseEnter={() => setActive({ name, amount, share: Math.round((amount / total) * 100) })} onMouseLeave={() => setActive(null)}><span className="legend-label"><i style={{ backgroundColor: chartColors[name] }} />{name}</span><span><strong>{money(amount)}</strong><small>{Math.round((amount / total) * 100)}%</small></span></li>)}</ul></div> : <p className="empty-chart">Your category allocation will appear here after you add an expense.</p>}</section> }
function CategoryIcon({ category }) { const props = { size: 18, strokeWidth: 1.8 }; if (category === 'Food & Dining') return <Utensils {...props} />; if (category === 'Transport') return <TrainFront {...props} />; if (category === 'Education') return <GraduationCap {...props} />; if (category === 'Entertainment') return <Coffee {...props} />; if (category === 'Shopping') return <ShoppingBag {...props} />; return <BookOpen {...props} /> }
function Expense({ item, onEdit, onDelete }) { return <article className="expense-row"><div className={`category-icon ${styles[item.category]}`}><CategoryIcon category={item.category} /></div><div className="expense-detail"><h3>{item.description}</h3><div><span className={`category-tag ${styles[item.category]}`}>{item.category}</span><time>{readableDate(item.date)}</time></div></div><div className="expense-amount"><strong>{money(item.amount)}</strong><div className="row-actions"><button type="button" onClick={onEdit} aria-label={`Edit ${item.description}`}><Pencil size={14} />Edit</button><button type="button" onClick={onDelete} aria-label={`Delete ${item.description}`}><Trash2 size={14} />Delete</button></div></div></article> }
function EmptyState() { return <div className="empty-state"><Search size={22} /><h3>Nothing found</h3><p>Try adjusting your search or category filter.</p></div> }
